services:
  db:
    image: postgres:15
    container_name: erasmus_crm_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: erasmus_crm
    ports:
      - "5432:5432"
    volumes:
      - erasmus_crm_pg:/var/lib/postgresql/data

volumes:
  erasmus_crm_pg:
